apiVersion: v1
kind: Service
metadata:
  name: ms-got
  labels:
    app: ms-got
spec:
  externalIPs:
  - 192.168.1.156
  - 88.196.63.92
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: ms-got
  type: NodePort
